FROM node:16-alpine3.16

LABEL version="1.0"
LABEL description="WaDevRencongAPI MERN"

WORKDIR /app

COPY ["package.json","package-lock.json*","npm-shrinkwrap.json*", "./"]

RUN npm install && npm cache clean --force

COPY . .

EXPOSE 5000

CMD ["npm", "run", "dev"]